### ISSUE TITLE
Clarify Callgrind Event Types

### ISSUE THREAD

**Issue by noisyboiler** [vpelletier/pprofile#20]
Hi @vpelletier 

Dumping stats to be visualised in CacheGrind gives us 3 costing options for inclusive and self sorting: hits, us, us/hit.

![screen shot 2016-12-08 at 09 07 59](https://cloud.githubusercontent.com/assets/113480/21004048/5fcba6d0-bd26-11e6-9c13-1f28d01c8623.png)

Could you clarify exactly what these Event Types are please?

Many thanks!

**Comment by vpelletier** [comment]
Hello,

us is microseconds.
hits is the number of times the line of code was executed.
us/hit is the ratio between both (ie, average execution time of each line).

**Comment by noisyboiler** [comment]
Great stuff @vpelletier.
Thanks
