### ISSUE TITLE
KCachegrind can't open `pprofile` output when command-line is long.

### ISSUE THREAD

**Issue by o11c** [vpelletier/pprofile#22]
The `cmds:` line should be at the *end* of the header, so that it can detect the `events:` header within a fixed number of bytes.

See https://cgit.kde.org/kcachegrind.git/commit/?id=c30a9694bca7e97808d97a9f07f6af46881e2ec9

**Comment by vpelletier** [comment]
Thanks for this perfect bug report !

This should be fixed in 1.10.1 .
