### ISSUE TITLE
Which versions of Python are supported? Looks like not Python 3.6

### ISSUE THREAD

**Issue by 1kastner** [vpelletier/pprofile#23]
I successfully installed this tool via the setup.py script. I would have preferred conda but it was not available at the channels I am subscribed to.

Then I ran this:
```
>>> import pprofile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Downloads\pprofile-master\pprofile.py", line 57, in <module>
    import cStringIO
ModuleNotFoundError: No module named 'cStringIO'
>>>
```

A check at the documentation showed that it was available for Python 2.7 [0] but not in Python 3 anymore [1]. Could it be possible to change pprofile so that it can work under Python 3.6 as well?

[0] https://docs.python.org/2/library/stringio.html
[1] https://docs.python.org/3.0/whatsnew/3.0.html

**Comment by vpelletier** [comment]
Hello,

For python3 support, you have to install the egg, as setup.py will then run 2to3 on the source to produce something which python3 accepts.

Feel free to reopen if 2to3 leaves code incompatible with python3 behind.

**Comment by 1kastner** [comment]
It worked, at least the module can be imported. For the others I will leave the needed steps below. Is it maybe even worth to put it in the README?
```
...\pprofile-master>python setup.py bdist_egg
cd dist
...\pprofile-master\dist>easy_install pprofile-1.11.0-py3.6.egg
```

**Comment by vpelletier** [comment]
About the steps, I tend to do:
```
$SOME_VENV/bin/python setup.py install
```
which installs the source without an intermediate egg building step (setup.py being compatible with 2 and 3, a single-step install is possible).

Or, to save also the step of cloning the repository:
```
$SOME_VENV/bin/pip install pprofile
```
as this egg is published on pypi.

Also, on several distributions ([Debian](https://packages.debian.org/search?keywords=python-pprofile), [Ubuntu](https://packages.ubuntu.com/search?keywords=python-pprofile), and maybe others) package pprofile, which is IMHO best suited for system-wide installation (I also see a [user package for arch](https://aur-dev.archlinux.org/packages/python-pprofile/), though rather outdated).

About documenting the install procedure, I hesitate: to me, `setup.py` is the standard way to install python modules, so it should ideally not need documentation.

OTOH, you are not the first person to report this incompatibility, so `setup.py` usage seems not as widespread as I thought. And I also like being able to run code straight out of repository, so I understand that having to run `setup.py` or `2to3` can be annoying.

**Comment by 1kastner** [comment]
First I used pip and ran into the struggle. As in general not everything is perfectly translated by 2to3, I did not want to try to port it to Python 3 without any background knowledge. If everything ran from the repository, that'd be great 👍

**Comment by vpelletier** [comment]
> First I used pip and ran into the struggle.

This would be a bug indeed. I could not reproduce it though:

```
$ virtualenv -p /usr/bin/python3 py3
[...]
$ py3/bin/pip install pprofile
[...]
Successfully installed pprofile-1.11.0
$ py3/bin/python
Python 3.5.4 (default, Sep  5 2017, 18:32:10)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pprofile
>>>
```

With ./pprofile.py being clean from git:

```
$ diff -u pprofile.py py3/lib/python3.5/site-packages/pprofile.py
--- pprofile.py 2017-07-23 23:58:25.603118321 +0000
+++ py3/lib/python3.5/site-packages/pprofile.py 2017-09-24 00:37:31.728099584 +0000
[...]
-import cStringIO
+import io
[...]
```

Maybe your pip ran with python2, but somehow python3 could still reach the installed egg ?

> in general not everything is perfectly translated by 2to3

True. In the case of pprofile (and a few other of my python modules), I try to check 2to3 diff regularly for sanity and to keep it minimal (for some definition of "minimal", which ignores "dict.iter*" differences for example). As I sometimes forget, I configured travis to run tests on python3 to check it at least runs.

**Comment by 1kastner** [comment]
Maybe the issue was related to python 2/3 confusion, now it is difficult for me to reproduce the issue.
