### ISSUE TITLE
this tool doesn't support multiprocess, right?

### ISSUE THREAD

**Issue by scotthuang1989** [vpelletier/pprofile#31]
I read through the documentation and also try it my self. this tool doesn't support multi-processing profiling, right?

**Comment by vpelletier** [comment]
Correct, on its own it does not do anything outside of the python process it is used in.

If you start it in multiple interconnected processes, you will get separate traces and whenver one process waits on IPC from another it will just show as that syscall/function waiting (ex: a  blocking read, or a blocking select/poll/...).

**Comment by scotthuang1989** [comment]
thanks for rthe quick answer, I will find other tools to do the job.
