### ISSUE TITLE
How to show profiling only for my script?

### ISSUE THREAD

**Issue by amorshedi** [vpelletier/pprofile#36]
Hi,
My question has already been asked [here](https://stackoverflow.com/questions/56795253/saving-pprofile-output-to-a-file).

Is it possible to show stats ONLY for the lines in my script file?

Thanks,
Ali

**Comment by vpelletier** [comment]
Thanks, I replied on stackoverflow directly. Sorry for not noticing your question earlier, I am not very active there.
