### ISSUE TITLE
Limiting the "depth" of the profile

### ISSUE THREAD

**Issue by tshmak** [vpelletier/pprofile#44]
pprofile seems to be a great tool. However, it is giving me too much output. Is there any way to limit the output? Basically, can I request only the times of the lines that I want to profile without going into the subroutines they are calling? More generally, can I control the "depth" into which the profiler will descend into when profiling? 

It seems from the README that the recommended method for using pprofile on larger projects is to use (q/k)cachegrind to visualize the results. However, it doesn't quite give me the line-by-line profile that I'm seeking. In particular, there are a number of 'import' statements in my scripts that I know are using up a lot of times, but they cannot be found in the profile at all. 

Any help would be much appreciated.

**Comment by vpelletier** [comment]
> More generally, can I control the "depth" into which the profiler will descend into when profiling?

At the moment at least, there is no easy control of this. Except maybe if you can express the restriction as which files should be included in the output, but this will not be enough if, for example, you have a lot of recursion within one file.

> In particular, there are a number of 'import' statements in my scripts that I know are using up a lot of times, but they cannot be found in the profile at all.

Import-time, if it was actually captured during profiling (which should be the case when using the pprofile command, as opposed to using it as a module) must be present in the profiling result, but may be masked by kcachegrind: it limits how long the function list is. But it should be possible to make them visible by searching for `<module>`:

```
$ pprofile --format callgrind -o test.cachegrind -m http.server -- --help
[...]
$ kcachegrind test.cachegrind
```
![image](https://user-images.githubusercontent.com/191204/155119813-454f3635-9a66-436a-b5bc-a42b36278f0f.png)

**Comment by tshmak** [comment]
Thanks for your help!
