### ISSUE TITLE
Return stats as a string

### ISSUE THREAD

**Issue by Miserlou** [vpelletier/pprofile#5]
Would be nice if there was a way to get the stats as a string, as I want them but I don't want them on stdout. Instead, I'm going to have to write them to a file, then read that file contents. Weird.

**Comment by vpelletier** [comment]
You can call `callgrind` or `annotate` providing a (|c)StringIO.StringIO instance, which will avoid going through an on-disk file.

FWIW, I recently pushed code to [use pprofile from inside zope](https://github.com/vpelletier/pprofile/blob/master/zpprofile.py), where one typically does not have access to server's filesystem. This poses two problems:
- I do not want to use a server-side temp file (directly, or indirectly via `zip` or `tar` modules) 
- I cannot access server's source code for trace inspection

So I generate an "archive" (actually, a MIMEMultipart) with not only the callgrind output, but also all involved source code. Look for `asMIMEString` method.

Hope this helps.
