### ISSUE TITLE
PyPI formatting is better in version 1.7.3 than in 1.8.3

### ISSUE THREAD

**Issue by nickjacobson** [vpelletier/pprofile#8]
Compare the look of https://pypi.python.org/pypi/pprofile/1.7.3 to https://pypi.python.org/pypi/pprofile/1.8.3

The 1.7.3 version has working HTML links, fonts, etc. but the 1.8.3 version is mostly plain text.

**Comment by vpelletier** [comment]
Nice catch. I think I remember seeing a discussion on distutils-sig about pypi page syntax changing. They were IIRC supposed to set a backward-compatible setting per-package, maybe it was per-package-version ?

**Comment by vpelletier** [comment]
...and fixed: there were two missing dashes below "Deterministic profiling" title.

**Comment by nickjacobson** [comment]
Ugh, I don't know why but please try loading https://pypi.python.org/pypi/pprofile/1.9 in Chrome. (I'm in version  51.0.2704.103.) Scroll to the bottom of the page. It's taking around 4-5 minutes to load the full page. I tried it on multiple computers and got the same result.

I tried it in IE11 and the latest Firefox (v47.0) and the page loads immediately.

**Comment by nickjacobson** [comment]
...the problem only happens some of the time. If it doesn't happen at first, try a few times.

As soon as you click a link on the page like https://pypi.python.org/pypi/pprofile/1.9#output the full page is immediately displayed and the problem is gone.

**Comment by nickjacobson** [comment]
I found that the same issue can happen with https://pypi.python.org/pypi/pprofile/1.7.3 so it isn't a new issue.
